server:
  port: 9002
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: consumer-service-gateway
          uri: lb://consumer-nacos-feign
          predicates:
            - Path=/consumer-service/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            allowCredentials: true
            maxAge: 3600000
    nacos:
      server-addr: http://192.168.0.107:8848
      username: nacos
      password: nacos
      discovery:
        namespace: public
    sentinel:
      transport:
        dashboard: http://127.0.0.1:9001
ribbon:
  eager-load:
    enabled: true
