server:
  port: 8084

spring:
  application:
    name: provider2-nacos
  cloud:
    nacos:
      server-addr: http://192.168.0.107:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
